# 侧边栏主菜单
[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
    [main.params]
        icon = "tag"

[[main]]
    identifier = "links"
    name = "链接"
    url = "/links/"
    weight = 4
    [main.params]
        icon = "link"


[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/WolfeOvO"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "X (Twitter)"
    url        = "https://x.com/_WolfeOvO_"

[[social]]
    identifier = "telegram"
    name       = "Telegram"
    url        = "https://t.me/WolfeOvO"

    [social.params]
        icon = "brand-twitter"
