# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = "Wolfe Group"

[dateFormat]
    published   = "åˆ›å»ºäº 2006å¹´1æœˆ2æ—¥ 15:04"
    lastUpdated = "æœ€åæ›´æ–°äº 2006å¹´1æœˆ2æ—¥ 15:04"

[sidebar]
    emoji    = "ğŸº"
    subtitle = "ä¸€ä¸ªæ™®æ™®é€šé€šçš„ä¸ªäººåšå®¢"
    avatar   = "img/avatar.png"

[article]
    headingAnchor = true
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "éµå¾ª CC BY-NC-SA 4.0 åè®®å‘å¸ƒï¼Œè½¬è½½æ—¶è¯·æ³¨æ˜æ¥æºï¼Œä¾µæƒå¿…ç©¶"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
